version: '3.9'

services:
  flask:
    build:
      context: ./PipeLineBlueprint/modelside
    container_name: flask-container
    ports:
      - "5003:5003"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "5002:80"
    depends_on:
      - flask
    restart: unless-stopped

  backend:
    build:
      context: ./authentication_end
    container_name: backend-container
    ports:
      - "5001:5001"
    env_file:
      - ./authentication_end/.env
    depends_on:
      - frontend
      - flask
    restart: unless-stopped
